apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "cicd.fullname" . }}
  labels: 
    app: {{ template "cicd.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
      app: {{ template "cicd.fullname" . }}
